version: '3.8'
services:
  app:
    container_name: html_server_training
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - type: bind
        source: .
        target: /workspace